#version: '2'
version: '2'

services:
  api:
    depends_on:
      - elasticsearch
    build:
      context: .
    #  target: api
    #image: exceptionless/api-ci:latest
    image: exceptionless/api:latest
    environment:
      EX_AppMode: Development
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80
    volumes:
      - appdata:/app/storage

  jobs:
    depends_on:
      - api
    build:
      context: .
    #  target: job
    #image: exceptionless/job-ci:latest
    image: exceptionless/job:latest
    command: run-all
    environment:
      EX_AppMode: Development
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - appdata:/app/storage

  ui:
    #image: exceptionless/ui-ci:latest
    image: exceptionless/ui:latest
    environment:
      AppMode: Development
      BaseUrl: https://exceptionless.dev.enumis.co.uk
    ports:
      - 5100:80

  elasticsearch:
    image: slideroom/elasticsearch:98
    environment:
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1 
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    depends_on:
      - elasticsearch
    image: slideroom/kibana:116
    ports:
      - 5601:5601

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
 
volumes:
  esdata:
    driver: local
  appdata:
    driver: local
